name: Terraform Deploy

#on:
#  push:
#    branches:
#      - main      # This will run the pipeline whenever you push code to the main branch

on:
  workflow_dispatch:   # Manual trigger 

permissions:
  issues: write
  pull-requests: write
  contents: read
  
jobs:
  terraform-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Move security group state
        run: |
          terraform state mv \
            aws_security_group.ec2_sg \
            module.ec2_sg.aws_security_group.sg

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest   
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
         
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/
        run: terraform plan

#      - name: Terraform Apply                # Auto Approval
#        working-directory: terraform/
#        run: terraform apply -auto-approve

  terraform-apply:
    name: Terraform Apply                     # Requires Approval
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Approval                # Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: Divij-007
          secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Apply                  # After Approval
        if: github.ref == 'refs/heads/main'    # This line ensures apply runs only on main
        working-directory: terraform/
        run: terraform apply -auto-approve
